apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "statuspage-exporter.fullname" . }}
  labels:
    {{- include "statuspage-exporter.labels" . | nindent 4 }}
data:
  HTTP_PORT: {{ .Values.httpPort | quote }}
  {{- if .Values.statuspages }}
  STATUSPAGES: {{ .Values.statuspages | join ", " | quote }}
  {{- end }}
  FETCH_DELAY: {{ .Values.fetchDelay | quote }}
  CLIENT_TIMEOUT: {{ .Values.clientTimeout | quote }}
