before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    binary: statuspage-exporter
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
dockers:
  # https://goreleaser.com/customization/docker/
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/fernandonogueira/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/fernandonogueira/{{ .ProjectName }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.description=Statuspage Exporter"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/fernandonogueira/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "ghcr.io/fernandonogueira/{{ .ProjectName }}:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.description=Statuspage Exporter"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    image_templates:
      - "ghcr.io/fernandonogueira/{{ .ProjectName }}:{{ .Version }}-armv7"
      - "ghcr.io/fernandonogueira/{{ .ProjectName }}:latest-armv7"
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.description=Statuspage Exporter"

docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  - name_template: ghcr.io/fernandonogueira/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/fernandonogueira/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/fernandonogueira/{{ .ProjectName }}:{{ .Version }}-arm64v8
      - ghcr.io/fernandonogueira/{{ .ProjectName }}:{{ .Version }}-armv7
  - name_template: ghcr.io/fernandonogueira/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/fernandonogueira/{{ .ProjectName }}:latest-amd64
      - ghcr.io/fernandonogueira/{{ .ProjectName }}:latest-arm64v8
      - ghcr.io/fernandonogueira/{{ .ProjectName }}:latest-armv7

archives:
  # https://goreleaser.com/customization/archive/
  - format: binary
    name_template: '{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  # https://goreleaser.com/customization/checksum/
  name_template: '{{ .ProjectName }}_v{{ .Version }}_checksums.txt'
snapshot:
  # https://goreleaser.com/customization/snapshots/
  name_template: "{{ incpatch .Version }}-SNAPSHOT"
source:
  # https://goreleaser.com/customization/source/
  enabled: true

release:
  prerelease: auto

changelog:
  use:
    github
  sort: asc
  groups: # Regex use RE2 syntax as defined here: https://github.com/google/re2/wiki/Syntax.
    - title: 'Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 300
    - title: 'Dependency updates'
      regexp: '^.*?(feat|fix|chore)\(deps?.+\)!?:.+$'
      order: 400
    - title: 'Other work'
      order: 999
